---
resources:
  - name: vault-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/boxboat/vault-rancher-masterclass

jobs:
  - name: vault-push
    public: true
    plan:
      - get: vault-repo
        trigger: true
      - task: vault-run
        file:
        config:
          inputs:
            - name: vault-repo
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: boxboat/concourse-vault
              tag: 'latest'

          inputs:
          - name: vault-repo
          run:

            path: ci/vault-auth.sh
            dir: vault-repo